(function(){
'use strict';
const API='https://fccvnotgsmxirhztveai.supabase.co/rest/v1/';
const KEY='sb_publishable__bDEEO_UuUc2AZmCNMhQHg_qzjmoSnL';
const svcHeaders=['نوع مقدم الخدمة','اسم مقدم الخدمة','رقم تلفون مقدم الخدمة','اسم الخدمة','سعر الخدمة'];
const caseHeaders=['اسم العميل','رقم العميل','المنطقة','اسم الحيوان','نوع الحيوان','العمر','اسم مقدم الخدمة','اسم الخدمة','تاريخ العملية','الوقت','المصدر','إجمالي العميل','مستحق مقدم الخدمة','عمولة PawApp','العميل سدد','مقدم الخدمة استلم','PawApp حصلت العمولة'];
let parsed=[],mode='services';
const $=id=>document.getElementById(id);
function role(){return window.PAWAPP_AUTH?.access?.role||document.body?.dataset?.pawRole||''}
function status(s){if($('importStatus'))$('importStatus').textContent=s}
function csv(rows){return '\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n')}
function parse(text){let rows=[],row=[],cell='',quoted=false; text=text.replace(/^\ufeff/,'');for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell.trim());cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell.trim());if(row.some(Boolean))rows.push(row);return rows}
function clean(v){return String(v||'').trim()}
function number(v){if(!clean(v))return null;const n=Number(clean(v));return Number.isFinite(n)&&n>=0?n:null}
function normalize(s){return clean(s).toLocaleLowerCase().replace(/\s+/g,' ')}
async function req(path,options={}){const token=window.PAWAPP_AUTH?.session?.access_token;if(!token)throw Error('سجلي الدخول أولاً');const response=await fetch(API+path,{...options,headers:{apikey:KEY,Authorization:'Bearer '+token,'Content-Type':'application/json',Prefer:'return=representation',...(options.headers||{})}});const raw=await response.text();if(!response.ok)throw Error(raw.slice(0,250));return raw?JSON.parse(raw):[]}
window.pawImportMode=function(m){mode=m;parsed=[];$('importFile').value='';$('importPreview').innerHTML='';$('importCommit').disabled=true;status(m==='services'?'قالب الخدمات: CSV، مع ربط مقدم الخدمة تلقائياً':'قالب العمليات: CSV، المعاينة متاحة؛ الاستيراد المالي يحتاج اعتماد الربط');}
window.pawDownloadTemplate=function(){const cols=mode==='services'?svcHeaders:caseHeaders;const blob=new Blob([csv([cols])],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=mode==='services'?'PawApp_Services_Template.csv':'PawApp_Old_Cases_Template.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
window.pawPreviewImport=async function(){if(role()!=='admin'){status('الاستيراد للـ Admin فقط');return}const file=$('importFile').files?.[0];if(!file){status('اختاري ملف CSV أولاً');return}if(!/\.csv$/i.test(file.name)){status('احفظي الملف بصيغة CSV ثم ارفعيه');return}const rows=parse(await file.text());const expected=mode==='services'?svcHeaders:caseHeaders;const actual=rows.shift()||[];if(expected.some((h,i)=>h!==actual[i])){status('عناوين الأعمدة غير مطابقة للقالب. نزّلي القالب من الصفحة.');return}parsed=rows.map((r,i)=>({line:i+2,values:r,valid:mode==='services'?!!clean(r[0])&&!!clean(r[1])&&!!clean(r[3])&&(clean(r[4])===''||number(r[4])!==null):!!clean(r[0])&&!!clean(r[1])}));const valid=parsed.filter(r=>r.valid).length;$('importPreview').innerHTML='<div class="hint">الإجمالي: '+parsed.length+' | صالح: '+valid+' | يحتاج مراجعة: '+(parsed.length-valid)+'</div>'+parsed.slice(0,25).map(r=>'<div class="card" style="padding:8px;margin:5px 0">'+(r.valid?'✓':'⚠')+' صف '+r.line+' — '+r.values.slice(0,5).map(x=>String(x).replace(/[&<>]/g,'')).join(' | ')+'</div>').join('');$('importCommit').disabled=mode!=='services'||valid!==parsed.length||!valid;status(mode==='services'?'راجعي المعاينة قبل الاستيراد':'استيراد العمليات المالية لم يُفعّل بعد؛ المعاينة فقط');};
window.pawCommitServicesImport=async function(){if(role()!=='admin'||mode!=='services'||!parsed.length||parsed.some(r=>!r.valid))return;if(!confirm('استيراد '+parsed.length+' خدمة ومقدم خدمة إلى TEST؟'))return;$('importCommit').disabled=true;let createdProviders=0,createdServices=0,skipped=0;try{const providers=await req('test_providers?select=id,name,provider_type,phone');const services=await req('test_services?select=id,provider_id,name');for(const item of parsed){const r=item.values;const type=/freelancer|فريلانسر|طبيب|دكتور/i.test(r[0])?'freelancer':'company';let p=providers.find(x=>normalize(x.name)===normalize(r[1]));if(!p){const saved=await req('test_providers',{method:'POST',body:JSON.stringify({name:clean(r[1]),provider_type:type,phone:clean(r[2])||null})});p=saved[0];providers.push(p);createdProviders++}if(services.some(x=>x.provider_id===p.id&&normalize(x.name)===normalize(r[3]))){skipped++;continue}const saved=await req('test_services',{method:'POST',body:JSON.stringify({provider_id:p.id,name:clean(r[3]),default_provider_price:number(r[4])})});services.push(saved[0]);createdServices++}status('تم في TEST: '+createdProviders+' مقدم خدمة جديد، '+createdServices+' خدمة، '+skipped+' مكرر. حدّثي الصفحة لرؤية البيانات.')}catch(e){status('توقف الاستيراد: '+e.message+' — أُضيف '+createdProviders+' مقدم و'+createdServices+' خدمة قبل التوقف. راجعي البيانات قبل الإعادة.')}};
})();